### ISSUE TITLE
Lock device is not working with Google Home, but works great with Alexa

### ISSUE THREAD

**Issue by societyofrobots** [sinricpro/non-sdk-issues#1]
Alexa is working fine with sinric pro, but Google Home does not. I posted all the specific details in [another thread](https://github.com/sinricpro/help-docs/issues/6#issuecomment-731696575), and you said repost here instead. Refer to that thread for details and all the steps I took to resolve the issue. (edit: it appears my original post detailing this issue has been deleted?)

> I think the time you tested the Google Home - SmartThings, Smart things had some connectivity network issues.

As of right now, still not working for me.

> I just tested the complete integration and all works fine. Make sure to change the device status to on/off on the server before you link the SmartThings-Google Home. Unless you don't do this the server doesn't know the current status of the device

I'm not sure what you mean by 'change the device status to on/off on the server'. Where do I find this?

In sinric pro dashboard, it says:
```
1 Online
Living Room
cabinet
Lock is Locked
```

Pushing Lock and Unlock in the dashboard works for controlling the device.

This is what SmartThings is showing me:

```
Display Name: cabinet
Device Location: My home
Device Network ID: SinricPro\|:SinricPro Smart Lock\|:5fac1d00cef123243fb06ec8
Status: ONLINE
Execution Location: Cloud
Last Activity: a few seconds ago
```

But, still doesn't work with Google Home after following your [tutorial](https://help.sinric.pro/pages/googlehome.html). Only works in Alexa.

I also tried posting this in the SmartThings forum, but my post has been in moderation for 12 days now and still not approved:
https://community.smartthings.com/t/211150

**Comment by kakopappa** [comment]
Oh. you are using a lock device type. Have you tried using aother device
types as switch to test the integration? I know there are some security
concerns related to lock device type being  by voice

**Comment by societyofrobots** [comment]
After I changed 'lock' to 'switch', GHA then recognized the device.
(I also changed from using your lock example code to your switch example code. I'll assume that's irrelevant.)

But, it's really odd to say "turn off the door" when I want to lock it.

Any suggestions on how I can fix this? Or, a way to turn off the security concern?
