### ISSUE TITLE
SinricPro - Connection unstable?

### ISSUE THREAD

**Issue by sim404** [sinricpro/non-sdk-issues#14]
SinricPro seems to be a bit unstable today (25th Feb 1800 GMT) and yesterday 24th too. I have a monitor around the Connected/Disconnected callback. It sends me a message over a Telegram Bot when the connection status changes. I also have a monitor on my WiFi connection and that’s currently solid but I suppose it could be my ISP. Ive seen some 16 disconnects starting around 1800 GMT today, most lasting less than a second, some a bit longer. Is there a problem?

**Comment by brentdcarlson** [comment]
I'm seeing the same issue over the same time frame.

**Comment by sim404** [comment]
It’s still happening. Approx 10 disconnects/reconnect around 1300 and 1500 GMT today. Also Alexa saying ‘not responding’ even though the switches are switching all being after a few seconds delay.

**Comment by kakopappa** [comment]
Yes, doing maintenance work. Posted in Facebook page already.

**Comment by sim404** [comment]
Ok, apologies - I don’t use Facebook.

**Comment by brentdcarlson** [comment]
We’re not all social (Facebook).  Would be nice to post something on GitHub or webpage.  Three days of up and down and we’re suppose to go hunt down maintenance on social media.

**Comment by peastuti** [comment]
Hi all, this is happening also today at this time

**Comment by kakopappa** [comment]
I can control devices at home just fine.. how about @sivar2311 ?

**Comment by sivar2311** [comment]
I had no issues here on my side - Activity log is clear and does not show any disconnects
(Except the daily 24hrs disconnect caused by my ISP)

**Comment by sim404** [comment]
I had a disconnect at 0400 GMT and again around 0730 GMT on 27th, both lasting less than a second. It’s been solid since then (UK). Thanks for sorting the initial problem.

**Comment by brentdcarlson** [comment]
Pleased to say I had no disconnects last night and my device had no reboots
(exception 29) caused by the sinric handler.

First time in weeks.

**Comment by brentdcarlson** [comment]
Take it back.  Multiple reboots and disconnect.  Ready to move on.  Can't
productize this.

**Comment by sivar2311** [comment]
@brentdcarlson Can you tell more about reboots and exception (29) ?
The SDK does not cause reboots, and there should be no exceptions!
This is the first time i heard about a user having reboots and exception(29) problems.

Can you provide more info about this?
- Which type of ESP do you use
- Does it happen on different ESP or is this only on one module?

Also please let me know the version of used
- Arduino ESP Core
- WebSockets Library
- SinricPro SDK

And  last but not least can you share the sketch (github repositroy / gitbhub gist)?

**Comment by brentdcarlson** [comment]
Wemos D1 R2 (ESP8266MOD) - only module I'm using for this device.
SinricPro SDK V2.9.0
Websockets V2.3.4
ESP8266 boards V2.7.4
Arduino IDE 1.8.13

#include "SinricPro.h"
#include "SinricProDimSwitch.h"

This device has IR remote control, OLED, time (NTPClient), temperature, OTA
and SMTPserver (to send me texts when reboots/startup).

So when I disable Sinric and use only with the remote, the device works
fine for days without any reboots.

Perhaps something stands out in the following exception decoder results:

*Exception 29: StoreProhibited: A store referenced a page mapped with
an attribute that does not permit stores*PC: 0x40222ca6:
*esp8266::MDNSImplementation::MDNSResponder::stcMDNS_RRAnswer::stcMDNS_RRAnswer(esp8266::MDNSImplementation::MDNSResponder::_enuAnswerType,
esp8266::MDNSImplementation::MDNSResponder::stcMDNS_RRHeader const&,
unsigned int)* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266mDNS\src\*LEAmDNS_Structs.cpp*
line *999*EXCVADDR: 0x00000008
Memory allocation of 544 bytes failed at 0x40223dda:
*esp8266::MDNSImplementation::MDNSResponder::_readRRAnswer(esp8266::MDNSImplementation::MDNSResponder::stcMDNS_RRAnswer*&)*
at C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266mDNS\src\*LEAmDNS_Transfer.cpp*
line *493*
*Decoding stack results*0x4021b8b4: *operator new(unsigned int)* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\*abi.cpp*
line *39*0x40223de4:
*esp8266::MDNSImplementation::MDNSResponder::_readRRAnswer(esp8266::MDNSImplementation::MDNSResponder::stcMDNS_RRAnswer*&)*
at C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266mDNS\src\*LEAmDNS_Transfer.cpp*
line *494*0x40220008: *_GLOBAL__sub_D_MDNS()* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266mDNS\src\*ESP8266mDNS.cpp*
line *9*0x40220d99:
*esp8266::MDNSImplementation::MDNSResponder::_parseQuery(esp8266::MDNSImplementation::MDNSResponder::stcMDNS_MsgHeader
const&)* at C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266mDNS\src\*LEAmDNS_Control.cpp*
line *321*0x4022fc19: *glue2esp_linkoutput* at glue-esp/*lwip-esp.c*
line *301*0x4022fea6: *new_linkoutput* at glue-lwip/*lwip-git.c* line
*260*0x401003d4: *ets_post(uint8, ETSSignal, ETSParam)* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\*core_esp8266_main.cpp*
line *177*0x401003d4: *ets_post(uint8, ETSSignal, ETSParam)* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\*core_esp8266_main.cpp*
line *177*0x401003d4: *ets_post(uint8, ETSSignal, ETSParam)* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\*core_esp8266_main.cpp*
line *177*0x402238d1:
*esp8266::MDNSImplementation::MDNSResponder::_udpReadBuffer(unsigned
char*, unsigned int)* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WiFi\src/include/*UdpContext.h*
line *361*0x40223c05:
*esp8266::MDNSImplementation::MDNSResponder::_udpRead16(unsigned
short&)* at C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266mDNS\src\*LEAmDNS_Transfer.cpp*
line *1061*0x40221a8d:
*esp8266::MDNSImplementation::MDNSResponder::_parseMessage()* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266mDNS\src\*LEAmDNS_Control.cpp*
line *141*0x40233aa6: *pbuf_free_LWIP2* at core/*pbuf.c* line
*786*0x4020a60a: *UdpContext::next()* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WiFi\src/include/*UdpContext.h*
line *338*0x40221df5:
*esp8266::MDNSImplementation::MDNSResponder::_process(bool)* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266mDNS\src\*LEAmDNS_Control.cpp*
line *81*0x40221e10:
*esp8266::MDNSImplementation::MDNSResponder::_callProcess()* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266mDNS\src\*LEAmDNS_Helpers.cpp*
line *197*0x4022619f: *std::_Function_handler
(esp8266::MDNSImplementation::MDNSResponder*)>
>::_M_invoke(std::_Any_data const&)* at
c:\users\brent\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\2.5.0-4-b40a506\xtensa-lx106-elf\include\c++\4.8.2/*functional*
line *2073*0x4020a044: *UdpContext::_s_recv(void*, udp_pcb*, pbuf*,
ip4_addr const*, unsigned short)* at
c:\users\brent\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\2.5.0-4-b40a506\xtensa-lx106-elf\include\c++\4.8.2/*functional*
line *2464*0x40234420: *udp_input* at core/*udp.c* line
*404*0x40239348: *ip4_input* at core/ipv4/*ip4.c* line
*1461*0x401010e3: *free(void*)* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\umm_malloc\*umm_malloc.cpp*
line *398*0x40230239: *ethernet_input_LWIP2* at netif/*ethernet.c*
line *188*0x40230058: *esp2glue_ethernet_input* at
glue-lwip/*lwip-git.c* line *469*0x4026443e: *ethernet_input* at
glue-esp/*lwip-esp.c* line *365*0x4026444f: *ethernet_input* at
glue-esp/*lwip-esp.c* line *373*0x401003d4: *ets_post(uint8,
ETSSignal, ETSParam)* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\*core_esp8266_main.cpp*
line *177*0x401003d4: *ets_post(uint8, ETSSignal, ETSParam)* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\*core_esp8266_main.cpp*
line *177*0x4022fc19: *glue2esp_linkoutput* at glue-esp/*lwip-esp.c*
line *301*0x401003d4: *ets_post(uint8, ETSSignal, ETSParam)* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\*core_esp8266_main.cpp*
line *177*0x401003d4: *ets_post(uint8, ETSSignal, ETSParam)* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\*core_esp8266_main.cpp*
line *177*0x401003d4: *ets_post(uint8, ETSSignal, ETSParam)* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\*core_esp8266_main.cpp*
line *177*0x4020a075: *WiFiUDP::available()* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WiFi\src\*WiFiUdp.cpp*
line *121*0x4020691c: *udpListener::handle()* at
C:\Users\brent\Documents\Arduino\libraries\SinricPro\src/*SinricProUDP.h*
line *43*0x402355fe: *tcp_output* at core/*tcp_out.c* line
*1361*0x40100e5f: *umm_free_core(void*)* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\umm_malloc\*umm_malloc.cpp*
line *351*0x401010e3: *free(void*)* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\umm_malloc\*umm_malloc.cpp*
line *398*0x40100758: *millis()* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\*core_esp8266_wiring.cpp*
line *188*0x4020a07b: *WiFiUDP::available()* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WiFi\src\*WiFiUdp.cpp*
line *121*0x4020691c: *udpListener::handle()* at
C:\Users\brent\Documents\Arduino\libraries\SinricPro\src/*SinricProUDP.h*
line *43*0x4021ba7c: *__esp_yield()* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\*core_esp8266_main.cpp*
line *119*0x4021c6d2: *__delay(unsigned long)* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\*core_esp8266_wiring.cpp*
line *54*0x4020961e: *ClientContext::wait_until_sent(int)* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WiFi\src/include/*ClientContext.h*
line *353*0x40100758: *millis()* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\*core_esp8266_wiring.cpp*
line *188*0x401003d4: *ets_post(uint8, ETSSignal, ETSParam)* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\*core_esp8266_main.cpp*
line *177*0x4021f952: *BearSSL::WiFiClientSecure::flush(unsigned int)*
at C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WiFi\src\*WiFiClientSecureBearSSL.cpp*
line *212*0x401003d4: *ets_post(uint8, ETSSignal, ETSParam)* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\*core_esp8266_main.cpp*
line *177*0x4021c6d2: *__delay(unsigned long)* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\*core_esp8266_wiring.cpp*
line *54*0x40100719: *millis()* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\*core_esp8266_wiring.cpp*
line *182*0x401006fd: *millis()* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\*core_esp8266_wiring.cpp*
line *176*0x401003d4: *ets_post(uint8, ETSSignal, ETSParam)* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\*core_esp8266_main.cpp*
line *177*0x40100758: *millis()* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\*core_esp8266_wiring.cpp*
line *188*0x4021baec: *optimistic_yield(uint32_t)* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\*core_esp8266_main.cpp*
line *151*0x4023f426: *br_ssl_engine_flush* at src/ssl/*ssl_engine.c*
line *1304*0x4021f8e7: *BearSSL::WiFiClientSecure::_run_until(unsigned
int, bool)* at C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WiFi\src\*WiFiClientSecureBearSSL.cpp*
line *554*0x4021ba70: *__esp_yield()* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266/*core_esp8266_features.h*
line *92*0x4021c6d2: *__delay(unsigned long)* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\*core_esp8266_wiring.cpp*
line *54*0x4020e818: *WebSocketsClient::handleClientData()* at
C:\Users\brent\Documents\Arduino\libraries\WebSockets\src\*WebSocketsClient.cpp*
line *583*0x40225734:
*WebSocketsClient::clientIsConnected(WSclient_t*)* at
C:\Users\brent\Documents\Arduino\libraries\WebSockets\src\*WebSocketsClient.cpp*
line *524*0x40221dfa:
*esp8266::MDNSImplementation::MDNSResponder::_process(bool)* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266mDNS\src\*LEAmDNS_Control.cpp*
line *93*0x40221ded:
*esp8266::MDNSImplementation::MDNSResponder::_process(bool)* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266mDNS\src\*LEAmDNS_Control.cpp*
line *90*0x40100758: *millis()* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\*core_esp8266_wiring.cpp*
line *188*0x4023f426: *br_ssl_engine_flush* at src/ssl/*ssl_engine.c*
line *1304*0x4021f8e7: *BearSSL::WiFiClientSecure::_run_until(unsigned
int, bool)* at C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WiFi\src\*WiFiClientSecureBearSSL.cpp*
line *554*0x40100700: *millis()* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\*core_esp8266_wiring.cpp*
line *175*0x4021fa89: *BearSSL::WiFiClientSecure::available()* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WiFi\src\*WiFiClientSecureBearSSL.cpp*
line *386*0x4021efc1: *BearSSL::WiFiClientSecure::connected()* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WiFi\src\*WiFiClientSecureBearSSL.cpp*
line *260*0x4020e9e6: *WebSocketsClient::loop()* at
C:\Users\brent\Documents\Arduino\libraries\WebSockets\src\*WebSocketsClient.cpp*
line *273*0x40206b12: *SinricProClass::handle()* at
C:\Users\brent\Documents\Arduino\libraries\SinricPro\src/*SinricPro.h*
line *264*0x40206bcf: *loop()* at
P:\Arduino\Sketches\WifiServerAlexa/*WifiServerAlexa.ino* line
*627*0x402077e8: *sendEmail()* at
P:\Arduino\Sketches\WifiServerAlexa/*WifiServerAlexa.ino* line
*1262*0x40201700: *std::_Function_handler::_M_invoke(const
std::_Any_data &, unsigned int, unsigned int)* at
c:\users\brent\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\2.5.0-4-b40a506\xtensa-lx106-elf\include\c++\4.8.2/*functional*
line *2073*0x401003d4: *ets_post(uint8, ETSSignal, ETSParam)* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\*core_esp8266_main.cpp*
line *177*0x4021bb94: *loop_wrapper()* at
C:\Users\brent\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\*core_esp8266_main.cpp*
line *197*

**Comment by sivar2311** [comment]
> Memory allocation of 544 bytes failed

There you have it! Your ESP is running out of memory!
Can you share your sketch please? 
upload to gist.github.com and share the link or send via e-mail please

**Comment by brentdcarlson** [comment]
Sketch uses 542332 bytes (51%) of program storage space. Maximum is 1044464
bytes.
Global variables use 33680 bytes (41%) of dynamic memory, leaving 48240
bytes for local variables. Maximum is 81920 bytes.

**Comment by sivar2311** [comment]
Yes, but the issue is about DYNAMIC MEMORY allocation. 
Forget about the numbers you see while compiling!

**Comment by brentdcarlson** [comment]
So adding Sinric is just putting me over the top.  Makes sense.  Any tools
to analyze this?

I assume porting to an ESP32 would solve my problem?

Thanks

**Comment by sivar2311** [comment]
The following sketch 
uses 262284 bytes (25.1%) of program storage space. Maximum is 1044464 bytes
Global variables use 27084 (33.1%) of dynamic memory, leaving 54.836 bytes for local variables. Maximum is 81920 bytes.


```C++
#include <Arduino.h>

#define SIZE 0x1000 // 4kb

void setup() {
  Serial.begin(115200); Serial.println();
}

void loop() {
  Serial.printf("Available memory: %d. Going to allocate %d bytes\r\n", ESP.getFreeHeap(), SIZE);
  delay(250);

  // allocate 1kb dynamic memory
  char *array = new char[SIZE];
  if (!array) {
    Serial.printf("Last memory allocation failed (not enough memory). array is pointing to \"nowhere\"! now i am writing to \"nowhere\" and let the ESP Crash ;)\r\n");
    delay(5000); // 5 seconds to read serial output before crash ;)
  }

  // fill up with zeros
  for (int i=0; i<SIZE; i++) array[i] = 0;

  // dynamic memory is not released! it will remain allocated which reduces the available memory in next round
}
```

**Comment by sivar2311** [comment]
Let the sketch above run and it will crash after a few seconds (out of memory / writing to invalid memory space -> Exception 29)

**Comment by sivar2311** [comment]
I didn't find an memory issues in SinricPro library and no other one complained about memory issues.

You said you use an OLED -> usually displays needs a lot of ram to store the pixel informations.
Somewhere must be a memory leak in your sketch or one of the used library (this does not exclude SinricPro SDK).

**Comment by brentdcarlson** [comment]
Thanks, I get it.  Wasn’t clear what the decoder was telling me.  I was tracing the stack dump and ignoring the bigger picture.

Thanks again

**Comment by sivar2311** [comment]
> I assume porting to an ESP32 would solve my problem?

No. The problem is
while your sketch is running something allocates dynamic memory without releasing it! (Memory leak!)
This will reduce the available memory over time. The more ram you have the longer it will take until the crash happens.

Please share your sketch. Maybe the issue is inside the sketch and i am able to find it (maybe not)... but i can give it a try.

**Comment by sivar2311** [comment]
Btw: This is reason and the answer for your comment in [esp8266-esp32-sdk issues #140](https://github.com/sinricpro/esp8266-esp32-sdk/issues/140#issuecomment-782611645)

**Comment by brentdcarlson** [comment]
Yes, agreed

**Comment by brentdcarlson** [comment]
Pulled the oled and it ran all night without crashing.  Not sure if it is responsible for a memory leak or just provided sufficient headroom.  I did see 20 Sinric connect/disconnects on the monitor.

For grins, I ported the device to an ESP32 protoboard design (yes, I understand your point if it is a memory leak).  I have everything working except it won’t connect to Sinric.  Anything special for ESP32 vs ESP8266?  Same handler and routines, same DNS, etc

Brent

**Comment by sivar2311** [comment]
> I did see 20 Sinric connect/disconnects on the monitor.

Woh, 20 connect/disconnects "without reason". That's a lot.
I suggest to log `ESP.getFreeHeap()` to serial monitor or to a file on FS periodically.

Difference for ESP32: No there aren't except `ESP8266WiFi.h` vs. `WiFi.h`
What's your ESP32 Core version?

**Comment by kakopappa** [comment]
Few disconnections are be related to the new version update yesterday

**Comment by brentdcarlson** [comment]
It is a ESP-WROOM-32.  Not sure how to get the core version.

Sinric debug shows:

platform:ESP32
version:2.9.0


My status dump:

Chip Revision: 1
Cores: 2
Features: 88
SDK Version: v3.3.4-432-g7a85334d8
CPU Freq: 240 MHz
Sketch size: 1095120 bytes
Flash Chip Size: 4194304 bytes
Free Heap: 244676 bytes


Sinric debug status:


[SinricPro:Websocket]: Connecting to WebSocket Server using SSL (
ws.sinric.pro)
[SinricPro:Websocket]: headers:
appkey:removed
deviceids: removed
restoredevicestates:false


I added the free heap dump to the ESP32 module (without connecting
successfully to Sinric) and heap remains relatively constant at:

Free Heap: 233296 bytes

**Comment by sivar2311** [comment]
> version:2.9.0

That's the SinricPro library version not esp-arduino core ;)

The issue have beein identified and a fix is in progress.

The esp-arduino core has changed - so the WebSockets library needs to be changed too
For this i opened an [issue in websockets](https://github.com/Links2004/arduinoWebSockets/issues/632) repository, as well as a  [pull request](https://github.com/Links2004/arduinoWebSockets/pull/633)

We have to wait until websockets library gets updated.
Until then you can use the `#define SINRICPRO_NOSSL` option.

**Comment by brentdcarlson** [comment]
Did the trick
