### ISSUE TITLE
information on custom devices

### ISSUE THREAD

**Issue by sgrizzi** [sinricpro/non-sdk-issues#17]
Hi,
I am looking into the possibility to use custom devices - quite powerful.
Three questions for clarification:
1 - is it correct that just one instance of the capabilities can be used per custom device? i.e. no chance to include two temperature sensors, or three switches, or other?
2 - the new custom device appears in Alexa (on an iPhone, for example) as a generic element with no possibility to manually control the internal capabilities - e.g. if the custom device contains a thermostat, I cannot see and control the thermostat mode, temperature, etc. Is this correct or am I doing something wrong?
3 - the list of capabilities is quite long, but I am missing a battery status indicator that would be useful for a portable device. Is, in general, a missing capability related to a limitation of Alexa (the feature is not handled) or to you writing the specific handler?
Regards, Gabriele

**Comment by sivar2311** [comment]
> 1 - is it correct that just one instance of the capabilities can be used per custom device? i.e. no chance to include two temperature sensors, or three switches, or other?

You can have multiple instances only for **generic controllers** (please see [alexa api generic controllers](https://developer.amazon.com/en-US/docs/alexa/device-apis/generic-controllers.html)).
Generic controllers are 
- range
- mode
- toggle (currently limited to 2 controllers) 

> 2 - the new custom device appears in Alexa (on an iPhone, for example) as a generic element with no possibility to manually control the internal capabilities - e.g. if the custom device contains a thermostat, I cannot see and control the thermostat mode, temperature, etc. Is this correct or am I doing something wrong?

There is a relationship to display category. Unfortunately alexa documentation does not tell much about display category and how this is interpreted by the alexa app. Developers are left to try and error on this point :(

> 3 - the list of capabilities is quite long, but I am missing a battery status indicator that would be useful for a portable device. Is, in general, a missing capability related to a limitation of Alexa (the feature is not handled) or to you writing the specific handler?

Afaik alexa doesn't have such a controller. But here is what i do:
- use a range controller instance
- send value periodically (`sendRangeValueEvent`) ([see my dimmerSensor device](https://gist.github.com/sivar2311/4a783a23a30493003c200d4c8ed9d051#file-main-ino-L76-L81)).
- ignore the value which is set in `onRangeValue callback` and return the value i want ([see my dimmerSensor device](https://gist.github.com/sivar2311/4a783a23a30493003c200d4c8ed9d051#file-main-ino-L100-L103)).

To trigger a routine, I simply use a ContactSensor controller. 

You can watch my dimmerSensor device on [youtube](https://www.youtube.com/watch?v=7cTZNaGRHww)

Regards,
Boris

**Comment by sivar2311** [comment]
Yeah, a doorbell event source should do the trick, too.

One cool thing about using range controller is: you can ask alexa for it's value :)
