### ISSUE TITLE
Ambient light sensor bh1750

### ISSUE THREAD

**Issue by 1975felix** [sinricpro/non-sdk-issues#19]
Hello, any way to interface ambient light bh1750 with sinricpro and alexa?

Thank

**Comment by sivar2311** [comment]
Since there were no further questions, I assume that everything has been answered.
For this reason, this issue is now closed.

If there are any further questions you can reopen this issue or create a new issue.

**Comment by 1975felix** [comment]
Hi sorry for late answer, have busy days.. you can close this issue and
thank for help

Il Dom 21 Mar 2021, 21:04 Boris Jäger ***@***.***> ha scritto:
