### ISSUE TITLE
garage door example not connecting properly

### ISSUE THREAD

**Issue by societyofrobots** [sinricpro/non-sdk-issues#2]
I need to use the command "unlock the door."

The 'lock' example works great in Alexa, but it doesn't show up as an icon in Google Home (GH). GH doesn't recognize it.

The 'switch' example works fine with both Alexa and GH. It shows up as a switch icon in GH. However, it's odd to say, "turn on the door."

The 'garage door' example shows up as a shield icon in GH. But when I say "open the door," it says "Sorry, it looks like that device hasn't been set up yet. You can do that in assistant settings." I'm lost on how to resolve this.

The garage door shows up as ONLINE in both the Sinric Pro Dashboard, and also ONLINE in smartthings.com/device/list. However in the SmartThings app, the garage door says, "Checking status..." indefinitely (instead of online or offline).

Ideas?

As a side note, [the garage door example](https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/src/SinricProGarageDoor.h) only allows to check if the door is open or closed, but not to command it to open or close.

**Comment by sivar2311** [comment]
> As a side note, the garage door example only allows to check if the door is open or closed, but not to command it to open or close.

- [`onLockState()`](https://sinricpro.github.io/esp8266-esp32-sdk/class_sinric_pro_lock.html#a2e4171a3cfcd3a87584fc114782ed4d8)
If you ask alexa to unlock your device, the `onLockState` callback is called. You have to implement the code here to unlock your door (like setting a pin HIGH for a certain amount of time to control an actor).

- [`sendLockStateEvent()`](https://sinricpro.github.io/esp8266-esp32-sdk/class_sinric_pro_lock.html#a3795d2fa1b8474239f46493915e70f1c)
If you lock / unlock the device manually, use `sendLockStateEvent()` to update the current state on SinricPro server.
(see [Lock_with_feedback.ino](https://github.com/sinricpro/esp8266-esp32-sdk/tree/master/examples/Lock/Lock_with_feedback))

If you have further questions about the SDK or SDK-examples, please open a seperated issue in the [SDK repository](https://github.com/sinricpro/esp8266-esp32-sdk/issues).

**Comment by sivar2311** [comment]
This issue is closed due to inactivity.
If you still have questions, please open a new issue.
