### ISSUE TITLE
Renewal

### ISSUE THREAD

**Issue by khorner116** [sinricpro/non-sdk-issues#20]
Hey guys.  Things have been going great until one of my subscriptions expired.  I can't figure out how to renew.  The Dashboard on the website allows my to see my subscriptions and create a new subscription, but not renew the expired one.  Help please.

**Comment by kakopappa** [comment]
Renewal option is in the menu with 3 dots

**Comment by kakopappa** [comment]
Login to Subscriptions then click on the menu option, drop-down list should have "Renew" option. 

![image](https://user-images.githubusercontent.com/7474406/111893742-593df880-8a37-11eb-8103-493828a4ad90.png)

**Comment by khorner116** [comment]
Got it.  thanks.
