### ISSUE TITLE
Retrieving data from the database

### ISSUE THREAD

**Issue by rcassinis** [sinricpro/non-sdk-issues#23]
Good day to everyone!

My question is: what is the best way to retrieve data from the database? Explanation: I have built a system that includes a NodeMCU that provides periodical data from a sensor (every minute, actually), and I have another NodeMCU that must, every minute, compare the last two data and drive a physical device. The data are in the database (the Sinric Pro web dashboard shows them9, but what is the best way to acquire them?
The two ESP must be separated for wiring reasons.
Any help will be much appreciated.

Riccardo

**Comment by kakopappa** [comment]
DB is not accessible via direct URL. You should consider a UDP solution.
