### ISSUE TITLE
Frequently facing delays on ESP32 homemade switch triggering

### ISSUE THREAD

**Issue by cefranco76** [sinricpro/non-sdk-issues#25]
Hi,

I'm facing some issues when I trigger switches, it takes too long to command to take effect, sometimes I receive a timeout message or the command is completly ignored, even when I switch in SinricPro APP. I use ESP32 homemade switches and has been working for almost two years with Sinric v1 without this kind of problems.

I had supposed that the problem was my code, cause I use other libraries as MQTT for example and there's a lot of stuff going on in my loop(){}. So, to get the proof, I uploaded the switch.ino sketch provided on ESP32 SDK and the problem persisted.

Switch's key used on tests ==> "60622b4141a7a97d3ef507b0"

![print2](https://user-images.githubusercontent.com/48095213/113792372-2c1e6500-971c-11eb-9c4b-e1bd62f76af3.jpg)
![print1](https://user-images.githubusercontent.com/48095213/113792376-2cb6fb80-971c-11eb-899c-1f10cb0c0c91.jpg)

**Comment by kakopappa** [comment]
After looking at the logs, it seems your ESP device has connection issues. It connects/drops which may be the reason why commands do not get through. Maybe it drops the connection because you are blocking the loop(). Since you haven't uploaded the complete code it's very hard for us to debug this. Example "Switch" sketch worked for me

You can see these connection/disconnections in the "Activity Log" in Portal.  

1. Enable debug logs in the SDK. Uncomment this line https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/examples/Switch/Switch/Switch.ino#L18
2.  Change the log level in Arduino 

![image](https://user-images.githubusercontent.com/7474406/113803705-47728a00-9787-11eb-92bc-b63d160c00d3.png)

3. Start a hotspot in your mobile. change the "Switch" sketch code to use the hotspot and connect to the server

**Comment by cefranco76** [comment]
Hi kakopappa,

I've followed your instructions and upload the oficial "Switch.ino" in a ESP32 device.
Approximately every five minutes the device is disconnected and connects again.

Is it normal? Is it related with my problem, in your opinion?!
![SwitchINO](https://user-images.githubusercontent.com/48095213/113940761-5b90a880-97d4-11eb-8f2d-b1d0f073d78d.png)
![SwitchINO_B](https://user-images.githubusercontent.com/48095213/113940765-5cc1d580-97d4-11eb-8336-2684193b2cb9.png)

**Comment by cefranco76** [comment]
Look at this....
![SwitchINO_C](https://user-images.githubusercontent.com/48095213/113949073-c3e78600-97e4-11eb-9a9f-e2828964c762.png)

**Comment by sivar2311** [comment]
Please set the ESP Core debug level as mentioned by kakaopappa to see what happens on your ESP-32's WiFi side. 
The SinricProDebug log is not sufficient for this, because it tells nothing about WiFi / SSL.

**Comment by kakopappa** [comment]
I did a test with the latest version of SDK / ESP-Core/ WebSocket. It connects once and you can see WebSocket is sending  heartbeats afterwards

![image](https://user-images.githubusercontent.com/7474406/113970078-5ed17600-9860-11eb-84c9-2399b4538a39.png)

**Comment by cefranco76** [comment]
Wel.... so it is!
Any ideia how to solve?


![SwitchINO_D](https://user-images.githubusercontent.com/48095213/114072765-fcd13a80-9878-11eb-83ed-3386f76728f7.png)

**Comment by sivar2311** [comment]
These are not issues.
1. Our SSL is not using certificates to verify the server - that's why you see "INSECURE" <- not an issue!
2. setOption is not an error. SSL connection is established <- not related to this issue

The log from above does not show any disconnections like the log you posted before.
Wether the time frame (5 mins) is to short, or the issue disappered due to some other reasons

**Comment by kakopappa** [comment]
whether you used a mobile hotspot vs WiFi is it same ?

**Comment by cefranco76** [comment]
Nope, here is the debug when connected over mobile phone hotspot...
It took a bit longer to appear the message "Cleanning SSL connection" and reconnect.

![SwitchINO_E](https://user-images.githubusercontent.com/48095213/114080039-4756b500-9881-11eb-8b32-fffaa070c54b.png)

**Comment by cefranco76** [comment]
> These are not issues.
> 
> 1. Our SSL is not using certificates to verify the server - that's why you see "INSECURE" <- not an issue!
> 2. setOption is not an error. SSL connection is established <- not related to this issue
> 
> The log from above does not show any disconnections like the log you posted before.
> Wether the time frame (5 mins) is to short, or the issue disappered due to some other reasons

Yeah, the disconnection doesn't appear, but notice that we have a new connection in a 5 minute interval.

**Comment by sivar2311** [comment]
Did you set your wifi router to a fixed channel? Or does your router switch wifi channels automaticly when a channel is "full" and a better chan el is available?

**Comment by sivar2311** [comment]
oh. i did not see that the last post was a screenshot from mobile hotspot connection.
So it happens on both wifi's? (Router and Mobile Hotspot)

**Comment by cefranco76** [comment]
> Did you set your wifi router to a fixed channel? Or does your router switch wifi channels automaticly when a channel is "full" and a better chan el is available?

![image](https://user-images.githubusercontent.com/48095213/114081361-d6180180-9882-11eb-8777-413e867cd897.png)

**Comment by cefranco76** [comment]
> oh. i did not see that the last post was a screenshot from mobile hotspot connection.
> So it happens on both wifi's? (Router and Mobile Hotspot)

Yes, the last debug print was over a mobile hotspot connection. But now with an unknown error code.

**Comment by sivar2311** [comment]
I set my router to a fixed channel, because the esp tends to disconnect on a channel change.

**Comment by cefranco76** [comment]
> I set my router to a fixed channel, because the esp tends to disconnect on a channel change.

Well, it worth a test! I'll do it and let you know later. Thanks.

**Comment by cefranco76** [comment]
It's clear the different behavior:

Here we've got a hotspot mobile connection
![SwitchINO_F](https://user-images.githubusercontent.com/48095213/114094122-5003b700-9892-11eb-973d-1eb77c8227cb.png)


And here, a WiFi connection with a fixed channel.
![SwitchINO_G](https://user-images.githubusercontent.com/48095213/114094151-585bf200-9892-11eb-9abe-f80ce9d6fe99.png)

**Comment by sivar2311** [comment]
Mobile Hotspot looks clean to me...
What's your conclusion on this?

**Comment by cefranco76** [comment]
I have no idea! 
Hope you can help me with some tip. Otherwise... I'll keep searching.

**Comment by cefranco76** [comment]
Although the disconnections are still happening, the switches turned more responsive after I reset to default some router configurations. I'd like to thank you guys for your time and hints. I'll keep monitoring.

**Comment by kakopappa** [comment]
Have you tried this on an ESP8266 board by any chance? If you do a google search for ["ssl_client.cpp UNKNOWN ERROR CODE (0050)"](https://www.google.com/search?q=ssl_client.cpp+UNKNOWN+ERROR+CODE+(0050)&rlz=1C1CHBF_enTH862TH862&oq=ssl_client.cpp+UNKNOWN+ERROR+CODE+(0050)&aqs=chrome..69i57.16974j0j4&sourceid=chrome&ie=UTF-8)  there are a lot of questions around this

**Comment by cefranco76** [comment]
> Have you tried this on an ESP8266 board by any chance

No, I haven't. I do not own any ESP8266 device.
Things got really better since last friday but yet with some disconnections.

I'll keep investigating, for sure.
