### ISSUE TITLE
App problems

### ISSUE THREAD

**Issue by timtolar** [sinricpro/non-sdk-issues#26]
Hi yesterday i set up the power monitor on the computer and after trying it out the app started to play around i got this error code. Can you help me what happened.

![A8A1609D-AF5B-48F1-8972-C893A14ACD59](https://user-images.githubusercontent.com/13749996/123505639-8e726c00-d660-11eb-991d-c513736957b9.png)

**Comment by kakopappa** [comment]
Are you using the latest version of the app?

**Comment by timtolar** [comment]
> Are you using the latest version of the app?
> […](#)

Yes i am 
![Uploading 8E0BB1C4-22D9-416C-97FA-1790F3E20B2E.png…]()

**Comment by kakopappa** [comment]
Hi @timtolar.

The image you have uploaded does not show up correctly on the Github. 

![image](https://user-images.githubusercontent.com/7474406/123507336-ff327c00-d692-11eb-8812-8bbdcdcd593f.png)

Can you confirm the version number please because fixed this issue in v2.12.1

**Comment by timtolar** [comment]
Hi yes i do have that version

![6C5052EB-2430-46E5-A158-48EF2F58F6DF](https://user-images.githubusercontent.com/13749996/123518613-f51a7880-d6a6-11eb-8fd2-e136f111965a.png)

**Comment by timtolar** [comment]
I dont have that version yet and i dont have an update available yet

**Comment by kakopappa** [comment]
I will push the 2.12.1 update to AppStore immediately

**Comment by timtolar** [comment]
Thanks very much.

**Comment by kakopappa** [comment]
New version is available in AppStore now

**Comment by timtolar** [comment]
It works now thank you very much!!
