### ISSUE TITLE
"Doorbell" functionality with google 

### ISSUE THREAD

**Issue by Ka11an** [sinricpro/non-sdk-issues#27]
Big fan of your work! Is there any plans to further support google home integration? I'd love to get my whole system running on Sinric Pro, however I'll have limitations with the doorbell and thermostat in particular.

**Comment by kakopappa** [comment]
Thanks.

Google Home doorbell requires a camera to stream the video according to
their documentation. We do not support video streaming at this time. We can
add Doorbell support once we figure it out

https://developers.google.com/assistant/smarthome/guides/doorbell

Thermostat - What’s the issue?
