### ISSUE TITLE
Google Home | Fan has only on/off without speed control

### ISSUE THREAD

**Issue by amitn** [sinricpro/non-sdk-issues#28]
In the Google home app fans (US) has only on/off without speed control

**Comment by kakopappa** [comment]
Hi,

Can you go to setting and see the device type?

**Comment by amitn** [comment]
![Screenshot_20210718-082336_Home](https://user-images.githubusercontent.com/1304248/126056782-ffc022ba-72ea-4903-9c51-be485a5327f4.jpg)
