### ISSUE TITLE
Unable to select anything other than default app key

### ISSUE THREAD

**Issue by MickTheGinge** [sinricpro/non-sdk-issues#32]
In the sinricpro web interface I have created additional APP KEYs, as recommended, one per hardware device, however I don't seem to be able to select them. Looked for documentation but didn't find any. What do I need to do, in the interface, to select a different APP KEY?

Note, I created only new APP KEYs, not APP and Secret 

Thanks

All my devices are using default app key which isn't great

**Comment by sivar2311** [comment]
Looks like you created API keys, not APP Keys (they will always come together with an APP Secret).
API Keys are used to access the web API.
APP Key + Secret are used for the SDK side.

![image](https://user-images.githubusercontent.com/2558564/135512719-1983e805-7b8d-4de4-a480-0d015f295e89.png)

When you create or edit an existing device you can choose the APP Key
![image](https://user-images.githubusercontent.com/2558564/135512817-f8e5b488-eadb-4cd6-97cb-b6aea71b930c.png)

**Comment by MickTheGinge** [comment]
Yep, user error, sorry. THANKS
