### ISSUE TITLE
Alexa issue

### ISSUE THREAD

**Issue by bevangg** [sinricpro/non-sdk-issues#35]
Hi 
I have ESP8266 relay modules that I have updated to Sinric Pro. I have managed to get them working through the Sinric Pro web interface and the Alexa Android app but my Echos will not work and say "Sorry xxxxxxxx is not responding". I have tried removing and scanning for new devices and relinking the account / skill to no avail. Please advise
Best regards
Bevan

**Comment by kakopappa** [comment]
1. do you have another device with the same name?
2.  does relinking the account the account, show the device in the alexa app?
3. Share the device id or email via support at sinric com email. I can take a look at the logs

**Comment by bevangg** [comment]
No way am I sending you my device logs, goodbye and thanks for the fish

**Comment by sivar2311** [comment]
Does the old (Sinric) device still exist in the account ?
It is strange that the control via the Alexa app works, but not the voice control.
