### ISSUE TITLE
My API request not works

### ISSUE THREAD

**Issue by Bitcraze26** [sinricpro/non-sdk-issues#37]
Hello everyone!
I made a simple API request for a contact sensor:

> https://api.sinric.pro/api/v1/devices/61d7718a1d53xxxxxxxx/action?clientId=nodejs-app&type=request&createdAt=1641573257&action=setContactState&value={"state": "open"}

Request status "200 OK"
Body response:

> {
    "success": true,
    "message": "OK. Il tuo messaggio è stato messo in coda per l'elaborazione."
}

But In alexa i can't get update for this sensor.
I had just one shoot for the first time about 1 hour ago and after no more updates of the states while the requests are sended succesfully.

What can be the problem?
Thanks!

**Comment by kakopappa** [comment]
Try with this
https://api.sinric.pro/api/v1/devices/61d7718a1d53xxxxxxxx/action?clientId=**portal**&type=request&createdAt=1641573257&action=setContactState&value={"state": "open"}

**Comment by Bitcraze26** [comment]
No, it doesn't work!
On my dashboard in portal it works like a charm, but not with API

**Comment by kakopappa** [comment]
Hi,

Can you please check these two things?

1. Set the clientId=portal in the login request.
2. Set the clientId=portal in the /action API call.

**Comment by Bitcraze26** [comment]
> Hi,
> 
> Can you please check these two things?
> 
> 1. Set the clientId=portal in the login request.
> 2. Set the clientId=portal in the /action API call.

I've created new login with clientId = portal, clientId=portal in /action API call but nothing changed.
Same with PostMan

Same success = true for every request but no updates on alexa

**Comment by Bitcraze26** [comment]
I've resolved.
For contact sensor the type on request bust be 'event':

type=event

> https://api.sinric.pro/api/v1/devices/61d771xxxxxxxx/action?clientId=portal&type=**event**&createdAt={{$timestamp}}&action=setContactState&value={"state": "open"}

Thanks!!
