### ISSUE TITLE
multiple "OK" errors followed by a success

### ISSUE THREAD

**Issue by DrakeAnglin** [sinricpro/non-sdk-issues#40]
[ref](https://github.com/sinricpro/esp8266-esp32-sdk/issues/258)

When I send one command to a device, I am getting several red "OK" toast followed by a success.

![image](https://user-images.githubusercontent.com/37958526/155771671-f65f1064-3084-4e11-9ffb-987eaf5f4bce.png)
![image](https://user-images.githubusercontent.com/37958526/155771743-90fd368f-1725-4c21-a156-84195ea5189c.png)

**Comment by kakopappa** [comment]
1. Please enable the SDK logs.

To do that add the following line to top of the sketch or uncomment it if’s
already in the sketch

#define ENABLE_DEBUG
2. Simulate the problem and copy the log from Arduino Serial Monitor and
paste it here.
