### ISSUE TITLE
Google Home Screen - Thermometer Sketch - Disabled mode

### ISSUE THREAD

**Issue by pmsalvino** [sinricpro/non-sdk-issues#42]
Hi! I’m using the thermometer sketch and so far I manage to connect to Sinric Pro, see data at Sinric Pro webpage and at Google Home app but I’m getting a “strange” message and screen for the device:
1- At Google Home app (Main page) in the device icon the temperature keeps switching between temperature and “disabled” every 5 seconds.
2- At Google Home Mini (device) if I ask what is the temperature, it tells me the correct temperature but followed by “device’s name is in disabled mode”.

I believe this “disabled mode” is responsible somehow for the screen below taken from inside device’s icon in Google Home app. 

Can you please check if it happens to somebody else?

![7075821E-021C-4619-968A-5B2B0708808D](https://user-images.githubusercontent.com/98078049/169139116-0aebcdcd-9aa0-4d52-bc34-df81c02093e6.png)

**Comment by pmsalvino** [comment]
> Hi @pmsalvino!
> 
> Which sketch are you using exactly? (There is no thermometer sketch in the examples).

I’m using the following exemple:
[esp8266-esp32-sdk](https://github.com/sinricpro/esp8266-esp32-sdk)/[examples](https://github.com/sinricpro/esp8266-esp32-sdk/tree/master/examples)/[temperaturesensor](https://github.com/sinricpro/esp8266-esp32-sdk/tree/master/examples/temperaturesensor)/DHT22/

**Comment by pmsalvino** [comment]
> Hi @pmsalvino
> 
> It's likely because you still haven't set the mode yet. There was an issue when the mode is not yet set, the server sets the default mode to 'none' which does not fall within the list of available modes and I have fixed it. Can you please check again?
> 
> If you still have issues, please set the mode and see whether you experience the same issue. if Yes, please drop us an email with your device id

There seems to be some changes in the Google Home app screen. I haven’t had the chance to make any updates to the sketch but screen is already different (and better). 

About setting the mode….I’m still in doubt how to do so. I’m using the following exemple: [esp8266-esp32-sdk](https://github.com/sinricpro/esp8266-esp32-sdk)/[examples](https://github.com/sinricpro/esp8266-esp32-sdk/tree/master/examples)/[temperaturesensor](https://github.com/sinricpro/esp8266-esp32-sdk/tree/master/examples/temperaturesensor)/[DHT22](https://github.com/sinricpro/esp8266-esp32-sdk/tree/master/examples/temperaturesensor/DHT22)/DHT22.ino

Couldn’t found where I can change the mode there. Is it available at Sinric pro Website or app? 

Below is the current screen I get from Google Home app. 
![037829F9-FE2A-4A5F-B3F6-BB3A0C87D829](https://user-images.githubusercontent.com/98078049/169225220-81bee882-921a-467d-a474-6c21c8c9b5bd.png)

**Comment by sivar2311** [comment]
The reason is, Google Home does not know temperature sensors.
A SinricPro temperature sensor is registered with Google as a thermostat.
For Google Home it is more appropriate to use a SinricsPro thermostat.

**Comment by pmsalvino** [comment]
> The reason is, Google Home does not know temperature sensors.
> A SinricPro temperature sensor is registered with Google as a thermostat.
> For Google Home it is more appropriate to use a SinricsPro thermostat.

I have already realized that Temperature Sensors were based on Thermostat at Google Home App, but the Sketch for Temperature Sensors seem to me easier to use than the Thermostat one. I’ll try to edit the Thermostat sketch in order to have data at Google Home app. So far I couldn’t change mode using the Temperature Sensors sketch. 

I’ll close the issue as a believe there will be no further developments in the Temperature Sensor sketch to allow changing the mode. In case a have any issue with Thermostat, I’ll send an email first. 

Thanks for the help.
