### ISSUE TITLE
AC temperature and humidity sensor

### ISSUE THREAD

**Issue by smoi** [sinricpro/non-sdk-issues#44]
Hello,

in the Sinric app there are the indoor temperature and humidity for AC devices but it looks like there are no method exposed to update them like in the SinricProThermostat, am I missing something? 

I've tried doing this using the AC ID but it gives me error

`SinricProThermostat &mySensor = SinricPro[ACUNIT_ID];  
  bool success = mySensor.sendTemperatureEvent(temperature, humidity);`

**Comment by kakopappa** [comment]
Hi @smoi 

Current implementation for for AC Unit does not support `[sendTemperatureEvent](https://sinricpro.github.io/esp8266-esp32-sdk/class_sinric_pro_window_a_c.html)`. 

Instead, you must use a Thermostat device type for now: Here's an example code
 https://github.com/sinricpro/non-sdk-issues/issues/43#issuecomment-1145494578
