### ISSUE TITLE
Can't connect sinric pro to Google Home

### ISSUE THREAD

**Issue by tlalani** [sinricpro/non-sdk-issues#47]
I am unable to connect my devices from sinric pro to google home. I'm not 100% sure if this is an issue on my end, but it seems like I can control my esp32 from the sinric pro app. When I go to the devices list, I see that it says `powerstate off` and I'm not sure if that's getting filtered out for some reason because of that.

In Google Home: 

![Screenshot_20220812-112349_Google](https://user-images.githubusercontent.com/104049126/184401866-e3cc30c7-e3e8-4dac-be3a-db056c14e978.jpg)

In Sinric Pro:

![image](https://user-images.githubusercontent.com/104049126/184402120-5e7efd76-4620-4dda-9e94-69d10de56d06.png)

**Comment by kakopappa** [comment]
Hi @tlalani ,

Looks like you are using a custom device type. Custom device types are not supported in Google Home and there's a warning when you create a device using a Template. 

Try built-in device type: Blind if that helps

![image](https://user-images.githubusercontent.com/7474406/184469063-350b5daa-d36a-46e6-9c1c-750c039ba669.png)

**Comment by tlalani** [comment]
Got it, thanks I hadn't seen that

**Comment by kakopappa** [comment]
GH not supported. Not an issue
