### ISSUE TITLE
setPercentage instead of setBrightness

### ISSUE THREAD

**Issue by marcoaltomonte** [sinricpro/non-sdk-issues#49]
SinricPro Android app is sending a setPercentage message instead of a setBrightness message to custom lights in the device specific page (an error message is shown, saying: Device did not handle "setPercentange").
The brightness action in the scene page sends setBrightness instead.

**Comment by kakopappa** [comment]
Hi @marcoaltomonte 

Can you share the template, please? You can open the template and click on export in the portal.

**Comment by marcoaltomonte** [comment]
{
  "name": "CustomLight",
  "description": "CustomLight",
  "deviceTypeId": "600d0e7194acbe29a9ce1fee",
  "capabilities": [
    {
      "id": "5ff0b30e994fd31b7d5e865b"
    },
    {
      "id": "5ff0b41b994fd31b7d5e8961",
      "mode": {
        "instanceId": "instanceid_0",
        "locale": "en-US",
        "modeName": "mode",
        "nonControllable": false,
        "modeValues": [
          "static",
          "animated"
        ]
      }
    },
    {
      "id": "5fff1358e6ec294399ae38db"
    },
    {
      "id": "6001c04c6dd0b8f904ef3eb3"
    }
  ]
}

Il giorno lun 5 dic 2022 alle ore 08:09 Aruna Tennakoon <
***@***.***> ha scritto:

**Comment by kakopappa** [comment]
Thanks. This issue will be fixed in the next release (2.17) which is scheduled to release at the end of this week. I will update this issue again when the fix is in Google Play

**Comment by kakopappa** [comment]
Sorry forgot to update this issue . Fix is available with the current version (2.17)
