### ISSUE TITLE
Cannot use a Temperature Sensor as an Alexa Trigger

### ISSUE THREAD

**Issue by stephenmott** [sinricpro/non-sdk-issues#5]
I created a temperature sensor, seems to all be working OK, shows up in the Alexa app, I can ask Alexa for it's temperature, happily reports back to the server dashboard, but when I try and create a routine and use it as a 'When this happens' trigger, it doesn't show up in the device list (although other commercial sensors do show up, so I know it should be possible).

**Comment by kakopappa** [comment]
@stephenmott This is the official response from Alexa Developer Help Ticket

```
Subject: RE:[CASE 7663399111] Temperature sensors do not show when creating a routine

Hello and thank you very much for following up.

I did a double check on our end and it looks like that only the temperature sensors built into Echo devices are supported for routines.

The Alexa.TemperatureSensor Interface does not support this feature.

```

you mentioned "other commercial sensors do show up", can you share which one ?

**Comment by stephenmott** [comment]
The one I have that shows up, is:

[SONOFF SNZB-02 ZigBee Mini Indoor Temperature and Humidity Sensor for Checking The Room Climate, SONOFF ZigBee Bridge Required, Compatible with Alexa/Google Home by sonoff, Amazon UK link](https://smile.amazon.co.uk/dp/B08BFW697F/ref=cm_sw_em_r_mt_dp_qfMXFbHYAA9T1?_encoding=UTF8&psc=1 )

N.B. it's connected directly to an Echo Plus (2nd gen.) via it's ZigBee interface rather than a hub, they say the only problem doing this is the humidity side doesn't work, but the temp side seems to work fine (just low temp, I want to connect up a K type thermocouple).

**Comment by kakopappa** [comment]
@stephenmott Thanks. Does it work without SONOFF Skill being activated?

**Comment by stephenmott** [comment]
It uses the eWeLink Skill for the gateway, but the device isn't registered on it, but I've disabled the skill & it still works.

**Comment by sivar2311** [comment]
This is the main difference. The Sonoff communicates directly with the Echo-Plus via the ZigBee interface. No skill is required for this. The Echo Plus itself is then able to trigger the temperature event.

**Comment by stephenmott** [comment]
That's true, but it's not really 'internal' to the Echo-Plus.. Hopefully they'll update it at some point..

**Comment by sivar2311** [comment]
It's not internal, but it's a direct communication between the Echo Plus device and the Sonoff device (via zigbee). 
This is completly different to WiFi based smart home devices which have to communicate via the manufacturers cloud and skill to amazon's cloud services. Which ends up in different interfaces with different capabilities. Like the amazon support wrote, Alexa TemperatureSensor Interface (which is used by skills) doesnt suport to trigger routines :(

**Comment by stephenmott** [comment]
Well hopefully they'll add support for it at some point, seems a bit limited without it..

**Comment by sivar2311** [comment]
Yes, that's true. Unfortunatley even skills are not (yet) to trigger routines directly.

As a workaround you can use 2 devices in your sketch: a thermostat and a contact (or motion) sensor.
The thermostat can be used to set the trigger temperature (set point temperature). If the temperature is reaching the target temperature, use the contact sensor to send a contactSensorEvent. This event can be used as a trigger for routines.

**Comment by stephenmott** [comment]
Thanks for the idea, I'll give it a go.. :)

**Comment by sivar2311** [comment]
This issue is closed due to inactivity.
If you still have questions, please open a new issue.
