### ISSUE TITLE
ModeController support on web and android app

### ISSUE THREAD

**Issue by marcoaltomonte** [sinricpro/non-sdk-issues#50]
Scenes page on the web let me add a "Set mode to" action for a mode controller of a custom device, but don't let me chose one of the possible values I setup earlier (combo box is empty).
The "mode" button on the Dashboard page works correctly instead.

Android app Scene page does not support mode controllers for custom devices (but specific device page works).

**Comment by kakopappa** [comment]
Thanks for reporting this issue.  

For now, Please create the scene in the Portal (Web) and run it in the app.  This also will be fixed in the next release (2.17)

**Comment by kakopappa** [comment]
Sorry forgot to update this issue . Fix is available with the current version (2.17)
