### ISSUE TITLE
Thermostat set Range in app

### ISSUE THREAD

**Issue by rob0591** [sinricpro/non-sdk-issues#52]
Not an issue as such but to me a puzzle where to change the range coverage in the app.  
I'm using Android and the app successfully with an ESP8266. It all works but the app temperature range only goes from 18 to 31 celsius.
I cant find any way to have a lower range start temperature, say 5 degrees to 31
Thanks

**Comment by kakopappa** [comment]
Hi @rob0591 

Thanks! 

I got the max-min temperature values from a thermostat available here (in Thailand). They go from 18-31... I see that it's not the same as the rest of the world. I will fix it in the next release

![image](https://user-images.githubusercontent.com/7474406/214170767-565ab12b-4d0d-46c4-aaac-6fdae4c6b53f.png)

**Comment by rob0591** [comment]
Many thanks.  Yes we are not all in warm climates :-)

**Comment by kakopappa** [comment]
v2.17.4 was released to Google Play with this change. Should be available shortly

**Comment by rob0591** [comment]
Thanks, it now has a decent range. However I now have an issue with the 'tiles' overprinting on screen.
![Screenshot_20230124_132448_Sinric Pro](https://user-images.githubusercontent.com/123417197/214309087-2fd287bb-337d-4547-959a-00b521af3b30.jpg)

**Comment by kakopappa** [comment]
This is what it looks like to me.

![Screenshot_1674568013](https://user-images.githubusercontent.com/7474406/214311316-d339da39-33a8-486a-8444-313680e91b27.png)

Can you share the phone model? also have you changed any font scaling settings in Android ?

**Comment by rob0591** [comment]
Ah yes fonts.  I can get the correct look as yours but the font is set to its smallest setting.  This makes it extremely small throughout the phone.
I will leave it at the normal setting so I can see the icon texts :-)

Phone is a Samsung Galaxy S20 5G

**Comment by rob0591** [comment]
How do I input a temperature for the outside temperature feature on the thermostat ?

**Comment by kakopappa** [comment]
Outside temperature is picked up from openweathermap api based on your location. it's not customizable yet.

**Comment by rob0591** [comment]
Ah ok.  Many thanks for your excellent work.

**Comment by rob0591** [comment]
Has the Apple version been updated with the greater range spread ?

**Comment by kakopappa** [comment]
@rob0591 just pushed the update to AppStore. once it gets approved will be available in AppStore.

**Comment by kakopappa** [comment]
should be available now.

**Comment by rob0591** [comment]
@kakopappa Many thanks it works perfect on my ipad.   I've made a YouTube video of my working thermostat jut need final two cables installing over weekend.
Video here :   https://youtu.be/fYfci6aYkr8

Rob

**Comment by kakopappa** [comment]
Thanks for sharing the video. It's nice to see these DIY hobby projects come to life with Sinric Pro 

I will fix this next time. 
![image](https://user-images.githubusercontent.com/7474406/216008336-cb658c4c-37c1-4133-8728-99da414bc6b5.png)
