### ISSUE TITLE
bug when calling create device api command

### ISSUE THREAD

**Issue by Geromatic** [sinricpro/non-sdk-issues#53]
I tried to add a device using the nodejs command. I am using arduino and json.  but when I submit the info to create a device is says name needs to be define yet I already did

{"id":"64042e541bb4e19c11ae4129","name":"hello there","productId":"5c5f72915ef9c024b423a046","roomId":"5c5f796140a15340803141c8"}
HTTP Response code: 422
"success" = false
"message" = "\"name\" is required"

**Comment by kakopappa** [comment]
Hi @Geromatic 

Since you have not posted the complete code or example code to reproduce the problem I am guessing your parameters are incorrect. Here's an example using nodejs fetch.
 

```
fetch("https://api.sinric.pro/api/v1/devices", {
  "headers": {
    "accept": "application/json, text/plain, */*",
    "authorization": "Bearer <TOKEN>" 
  },
  "body": "{\"name\":\"switch1\",\"description\":\"switch2\",\"productId\":\"5c67c4d4268198273c8551d0\",\"roomId\":\"<ROOMID>\",\"accessKeyId\":\"ACCESS_KEY_ID\",\"notifications\":{\"connection\":{\"whenConnected\":false,\"whenDisconnected\":false},\"turned\":{\"whenOn\":false,\"whenOff\":false},\"alert\":{\"enabled\":true}},\"timers\":{\"autoOnOff\":{\"on\":false,\"onInterval\":5,\"off\":false,\"offInterval\":5}},\"energyUsageEstimation\":{\"enabled\":false,\"type\":\"POWER\"}}",
  "method": "POST"
});
```

**Comment by Geromatic** [comment]
Still says same thing

`#include <WiFi.h>
#include <HTTPClient.h>
#include <Arduino_JSON.h>

const char* ssid = "xxxx";
const char* password = "xxxx";

//Your Domain name with URL path or IP address with path
const char* serverName = "https://api.sinric.pro";

bool doOnce = true;

void setup() {
  Serial.begin(115200);

  WiFi.begin(ssid, password);
  Serial.println("Connecting");
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("");
  Serial.print("Connected to WiFi network with IP Address: ");
  Serial.println(WiFi.localIP());
}

void loop() {
  if (doOnce) {
    //Check WiFi connection status
    if (WiFi.status() == WL_CONNECTED) {
      doOnce = false;
      HTTPClient http;

      // Your Domain name with URL path or IP address with path
      http.begin(serverName);

      // Specify content-type header
      http.setURL("/api/v1/auth");
      http.addHeader("x-sinric-api-key", "xxx-xxx-xxx-xx");
      http.addHeader("Content-Type", "application/x-www-form-urlencoded");
      // Send HTTP POST request
      int httpResponseCode = http.POST("{}");

      String payload = http.getString();
      JSONVar myObject = JSON.parse(payload);

      // JSON.typeof(jsonVar) can be used to get the type of the var
      if (JSON.typeof(myObject) == "undefined") {
        Serial.println("Parsing input failed!");
        return;
      }

      // myObject.keys() can be used to get an array of all the keys in the object
      JSONVar keys = myObject.keys();
      
      for (int i = 0; i < keys.length(); i++) {
        JSONVar value = myObject[keys[i]];
        Serial.print(keys[i]);
        Serial.print(" = ");
        Serial.println(value);
      }


      String accessToken = myObject["accessToken"];
      Serial.print("\n");

      http.setURL("/api/v1/devices");
      http.addHeader("Authorization", "Bearer " + accessToken);
      http.addHeader("Content-Type", "application/x-www-form-urlencoded");

      String jsonString = "{\
        \"name\"\
        :\"switch1\"\
        ,\"description\":\"switch2\",\"productId\":\"5c67c4d4268198273c8551d0\",\"roomId\":\"<ROOM>\",\"accessKeyId\":\"<KEY>\",\"notifications\":{\"connection\":{\"whenConnected\":false,\"whenDisconnected\":false},\"turned\":{\"whenOn\":false,\"whenOff\":false},\"alert\":{\"enabled\":true}},\"timers\":{\"autoOnOff\":{\"on\":false,\"onInterval\":5,\"off\":false,\"offInterval\":5}},\"energyUsageEstimation\":{\"enabled\":false,\"type\":\"POWER\"}}";

      httpResponseCode = http.POST(jsonString);

      Serial.print("HTTP Response code: ");
      Serial.println(http.getString());

      payload = http.getString();
      myObject = JSON.parse(payload);

      // JSON.typeof(jsonVar) can be used to get the type of the var
      if (JSON.typeof(myObject) == "undefined") {
        Serial.println("Parsing input failed!");
        return;
      }

      // myObject.keys() can be used to get an array of all the keys in the object
      keys = myObject.keys();

      for (int i = 0; i < keys.length(); i++) {
        JSONVar value = myObject[keys[i]];
        Serial.print(keys[i]);
        Serial.print(" = ");
        Serial.println(value);
      }

      // Free resources
      http.end();
    } else {
      Serial.println("WiFi Disconnected");
    }
  }
}`

**Comment by kakopappa** [comment]
I think your issue is 
`http.addHeader("Content-Type", "application/x-www-form-urlencoded");`
should be
`http.addHeader("Content-Type", "application/json");`

![image](https://user-images.githubusercontent.com/7474406/222947179-c363c326-7e09-425e-a811-d40bc172e65c.png)

**Comment by Geromatic** [comment]
ty. btw is the access key the app or api key? or is it custom

**Comment by kakopappa** [comment]
you can use 

get the list of rooms:  https://api.sinric.pro/api/v1/rooms
get the list of credential : https://api.sinric.pro/api/v1/credentials/appkeyandsecret

**Comment by Geromatic** [comment]
one last note.  is it because I am using the free account that I get this error

HTTP Response code: {"success":false,"message":"Unauthorized!"}

**Comment by kakopappa** [comment]
No, Likely missing the authorization http header

**Comment by Geromatic** [comment]
It would be nice in the future that Arduino could be used for all the node.js commands.  I will think on it :)  it would really benefit everyone
