### ISSUE TITLE
Toggle and mode are broke

### ISSUE THREAD

**Issue by Geromatic** [sinricpro/non-sdk-issues#57]
I tried first setting up a togglebutton and told alexa to turn on [flash] for [dining room light].  Instead it calls the onPowerState.  also Alexa, set the [device name] to [mode name].  Alexa replies doesnt know what "flash" or even "flash mode" is or "I dont know how to set the dining room light to that setting".  I tried different phrases and words but it either call the onPowerState or Alexa tells me that it doesnt know how to set that setting.  I had set the toggle to Flash and mode to flash with values of Flash but still it doesnt know what to do.  I just simply trying to say Alex, flash the dining room light.

**Comment by sivar2311** [comment]
Hello @Geromatic

I just tested the toggle button and I can say: it is not broken.
Have you checked the functionality in the Alexa app?

Alexa is unfortunately very sensitive in voice recognition for custom devices. 
It often depends on what device you are basing it on and how the capabilities are named.

Please test the functionality in the Alexa app first.

For further analysis, please export your device template and make it available for analysis (Device Templates -> edit template / on page 2: "Export Template").
