### ISSUE TITLE
constructive feedback on user friendliness

### ISSUE THREAD

**Issue by societyofrobots** [sinricpro/non-sdk-issues#6]
This is more feedback than an issue.

I am interested in using your project/service, and could bring you many customers to your service.

However, the setup required is overly complex and not user-friendly. It requires the user to sign up for two third parties (Sinric and SmartThings), copy over keys, and use multiple phone apps. It would be a customer support nightmare if we went with this. All of this should be automated in the background.

We'd like a service where the customer turns on the ESP and just says, "Alexa, discover new devices" and it would work seamlessly.

There is another project that works with Alexa and does this already. But, it still lacks Google Home integration: https://github.com/vintlabs/fauxmoESP

**Comment by kakopappa** [comment]
@societyofrobots 

1. Passing keys and setting up the device can be done via the Sinric Pro app just like how you would configure any other product available in the market. We provide this as a part of our Pass solution. contact us on support at sinric.com for more details about PaSS

2. LAN device discovery works with only a few privileged manufactures and functionality is limited. Emulating a Belkin switch or another device does not always work (discovery issues) and I do not think that's the right way forward.

**Comment by sivar2311** [comment]
This issue is closed due to inactivity.
If you still have questions, please open a new issue.
