### ISSUE TITLE
[Bug] Multiple Records of Energy Consumption being created for same device

### ISSUE THREAD

**Issue by fpto** [sinricpro/non-sdk-issues#67]
For some reason multiple records are created for the same device when turning it on:

See: https://scontent.fsap12-2.fna.fbcdn.net/v/t1.15752-9/370228843_1066435571403052_4880248789456643644_n.png?_nc_cat=109&ccb=1-7&_nc_sid=ae9488&_nc_ohc=44O0bdNM6w4AX81IYZC&_nc_ht=scontent.fsap12-2.fna&oh=03_AdSC55jlRIiJi9ycG-ca5qL3axmPH3M5VsS4Ki488Zx42Q&oe=6511E6E9

This messes up energy tracking, since it records twice the same device session.

**Comment by kakopappa** [comment]
Hi @fpto 

tried to reproduce this, does not seem to happen. This is what i did,

1. Create a new device, set and set the consumption details as below:
![image](https://github.com/sinricpro/non-sdk-issues/assets/7474406/62296d30-3cb9-4d0b-b016-b73c6981fd5f)
2. Turn on the switch and wait for a while
3. Turn off the switch
4. Check consumption 

![image](https://github.com/sinricpro/non-sdk-issues/assets/7474406/336fce70-d7d3-4c13-851d-fe1582e498d3)

Can you please provide steps to reproduce this problem. May be I am missing something.

**Comment by fpto** [comment]
In that case My guess is that the issue happens if you click twice on "turn on" button, which sometimes happens. I would expect in that case to keep only the record for the latest "turn on" time stamp.

**Comment by fpto** [comment]
It keeps happening:
<img width="779" alt="image" src="https://github.com/sinricpro/non-sdk-issues/assets/1721951/f50b95d1-1dfb-4180-b756-be7bf0f4fc27">

**Comment by kakopappa** [comment]
Hi @fpto 

I tried the double turn-on scenario, still seeing only one in the grid,

![image](https://github.com/sinricpro/non-sdk-issues/assets/7474406/56d093a7-21df-4253-ab18-7f27d72e095d)
 
![image](https://github.com/sinricpro/non-sdk-issues/assets/7474406/944ee9e9-f10a-461a-8d27-b30c1e661c2d)

The current logic in the server is when you double turn on, it will replace the old turn-on time with the new turn-on time. 

Do you have the steps to reproduce this issue?

**Comment by kakopappa** [comment]
Ok found the root cause. it seems to be happening when you double turn off.

**Comment by kakopappa** [comment]
I have deployed the fix to the production server now. Going forward it should not write double entries. Will add a clear estimate button in the next release. Thanks!
