### ISSUE TITLE
Documentation on Alexa phrases by device

### ISSUE THREAD

**Issue by jimwsmith** [sinricpro/non-sdk-issues#7]
I have managed to get Thermostat, temperature sensor and Light to work but am struggling with Power Sensor (which seems to be called Energy sensor in some screens)

It connects and displays fine on the SinricPro dashboard but I cannot get the readings on Alexa.  I'm trying to read: voltage, current, power etc.

So where is the documentation on the Alexa phrases by device?

**Comment by kakopappa** [comment]
Hello @jimwsmith 

Alexa power consumption API (Alexa.DeviceUsage.Estimation API) is still in beta and not available to the public yet. Once it's available we will complete the Alexa integration until then you have to use Sinric Pro

https://developer.amazon.com/en-US/blogs/alexa/device-makers/2020/09/Help-Your-Customers-Track-Manage-and-Save-on-Energy-Usage-with-Alexas-New-Energy-Dashboard-Coming-Soon

**Comment by sivar2311** [comment]
This issue is closed due to inactivity.
If you still have questions, please open a new issue.
