### ISSUE TITLE
Phone App

### ISSUE THREAD

**Issue by khorner116** [sinricpro/non-sdk-issues#8]
I've been quite happy with the reliability and utility of the App on the iPhone.  Good work. I have one suggestion, it would be great if the current server status of the devices could be reflected on the app icons.  It's hard at a glance to tell if something is on or off, open or closed, online or offline.

**Comment by kakopappa** [comment]
@khorner116 Thanks for your feedback. 

When you visit the Rooms tab, it will show the turned on/off devices highlighted from app v2.9.4 from onwards. This version is already available in Google Play now

**Comment by khorner116** [comment]
You are fast.  thanks

ken
