### ISSUE TITLE
Range value does not save a preset with value 0

### ISSUE THREAD

**Issue by sivar2311** [sinricpro/non-sdk-issues#88]
Creating presets for a range value, the preset for value 0 is not saved:

![image](https://github.com/user-attachments/assets/d5d89790-1558-494f-be1f-a2284b38a591)

After saving:

![image](https://github.com/user-attachments/assets/63dc66cb-a310-4cef-bba3-9efd319b67b9)

Maybe a "NULL"-check error?

**Comment by kakopappa** [comment]
fixed
