### ISSUE TITLE
RangeValue: Issue with deleteting presets

### ISSUE THREAD

**Issue by sivar2311** [sinricpro/non-sdk-issues#89]
Removing all presets is not possible. At least there is a bug in handling this:

When editing the RangeValue the remove button ("`-`" sign) is missing.
![image](https://github.com/user-attachments/assets/a2419f97-a9bd-49d7-ba88-969f2a792fcd)

To delete the last preset you have to press the add button ("`+`" sign) first, which gives you the necessary remove button ("`-`" sign);
![image](https://github.com/user-attachments/assets/b174ac61-5f82-4f70-a8e5-3ad6e422596e)

**Comment by kakopappa** [comment]
fixed.
