### ISSUE TITLE
Graphs showing incorrect plot lines for real time, 6-hours, and 24-hours views on iPhone App

### ISSUE THREAD

**Issue by mhagerth** [sinricpro/non-sdk-issues#90]
On the Sinric Pro iPhone App, the dashboard graph is showing incorrect plot lines for real time, 6-hours, and 24-hours views. Note the humidity plot line in the attached screenshot.  Clicking on the plot line shows the correct data value in the details (below the graph), however the plot line value is more than double the actual data value. The views for month and year do not have this issue. Also, the browser based dashboard does not have this issue.

![SinricProAppValues](https://github.com/user-attachments/assets/61b1f95e-88bb-4ee5-ba63-127b5a766ddf)

**Comment by kakopappa** [comment]
Hi @mhagerth 

Can you please email your temp sensor device id to support at sinric.com ?

**Comment by kakopappa** [comment]
Issue has been fixed in 2.27.2 and just uploaded it to AppStore and GooglePlay. Should be available in 24 to 48 hours
